from app.crypto_engine import encrypt_text_with_aes


TRANSACTION_PAYLOAD = 'TXN|from=ACCT-7721|to=MERCHANT-450|amount=2450 PKR|nonce=884291'


def build_bank_mitm_state(scenario, defense_enabled=False, launched=True):
    if not launched:
        return build_standby_state(scenario, defense_enabled)

    encrypted = encrypt_text_with_aes(TRANSACTION_PAYLOAD) if defense_enabled else None
    captured_payload = encrypted['ciphertext'] if encrypted else TRANSACTION_PAYLOAD
    readable = not defense_enabled

    packets = [
        {
            'id': 'pkt-001',
            'time': '09:41:12',
            'source': 'Client',
            'target': 'Bank Gateway',
            'protocol': 'HTTP' if not defense_enabled else 'HTTPS',
            'status': 'in_transit',
            'readable': readable,
            'intercepted': False,
            'payload_preview': TRANSACTION_PAYLOAD if readable else encrypted['ciphertext'][:42],
        },
        {
            'id': 'pkt-002',
            'time': '09:41:16',
            'source': 'Attacker Relay',
            'target': 'Packet Capture',
            'protocol': 'MITM',
            'status': 'captured' if readable else 'blocked',
            'readable': readable,
            'intercepted': True,
            'payload_preview': captured_payload,
        },
        {
            'id': 'pkt-003',
            'time': '09:41:20',
            'source': 'Bank Gateway',
            'target': 'Bank API',
            'protocol': 'HTTP' if not defense_enabled else 'HTTPS',
            'status': 'forwarded' if readable else 'verified',
            'readable': readable,
            'intercepted': False,
            'payload_preview': 'Forwarded transaction request' if readable else 'Authenticated encrypted request',
        },
    ]

    return {
        'scenario': scenario,
        'launched': launched,
        'defense_enabled': defense_enabled,
        'attack_success': not defense_enabled,
        'channel': {
            'status': 'protected' if defense_enabled else 'exposed',
            'label': 'Encrypted Channel' if defense_enabled else 'Plaintext Channel',
            'algorithm': encrypted['algorithm'] if encrypted else 'None',
        },
        'metrics': build_metrics(defense_enabled),
        'packets': packets,
        'alerts': build_alerts(defense_enabled),
        'attack_logs': build_attack_logs(defense_enabled, captured_payload),
        'defense_logs': build_defense_logs(defense_enabled, encrypted),
        'defenses': build_defenses(defense_enabled),
    }


def build_standby_state(scenario, defense_enabled):
    return {
        'scenario': scenario,
        'launched': False,
        'defense_enabled': defense_enabled,
        'attack_success': False,
        'channel': {
            'status': 'standby',
            'label': 'Simulation Standby',
            'algorithm': 'AES-256-GCM ready' if defense_enabled else 'None',
        },
        'metrics': [
            {'label': 'Active Attacks', 'value': '00', 'trend': 'scenario paused', 'tone': 'blue'},
            {'label': 'Protected Channels', 'value': '01' if defense_enabled else '00', 'trend': 'operator controlled', 'tone': 'green'},
            {'label': 'Packets Observed', 'value': '000', 'trend': 'waiting for launch', 'tone': 'blue'},
            {'label': 'Alert Priority', 'value': 'P3', 'trend': 'no active incident', 'tone': 'yellow'},
        ],
        'packets': [],
        'alerts': [],
        'attack_logs': ['[standby] Bank MITM scenario is paused'],
        'defense_logs': ['[standby] Defender console waiting for simulation launch'],
        'defenses': build_defenses(defense_enabled),
    }


def build_metrics(defense_enabled):
    return [
        {'label': 'Active Attacks', 'value': '01', 'trend': 'MITM relay traced', 'tone': 'red'},
        {'label': 'Protected Channels', 'value': '01' if defense_enabled else '00', 'trend': 'AES-256 active' if defense_enabled else 'plaintext exposed', 'tone': 'green'},
        {'label': 'Packets Observed', 'value': '003', 'trend': 'generated by simulation engine', 'tone': 'blue'},
        {'label': 'Alert Priority', 'value': 'P2' if defense_enabled else 'P1', 'trend': 'attack blocked' if defense_enabled else 'data exposure', 'tone': 'yellow'},
    ]


def build_alerts(defense_enabled):
    if defense_enabled:
        return [
            {'time': '09:41:22', 'title': 'MITM relay blocked by encrypted payload', 'severity': 'Medium'},
            {'time': '09:41:18', 'title': 'Ciphertext capture detected', 'severity': 'Medium'},
            {'time': '09:41:15', 'title': 'Secure channel policy active', 'severity': 'Low'},
        ]

    return [
        {'time': '09:41:22', 'title': 'Plaintext transaction exposed', 'severity': 'Critical'},
        {'time': '09:41:18', 'title': 'Replay buffer received transaction token', 'severity': 'High'},
        {'time': '09:41:15', 'title': 'Unencrypted transfer detected', 'severity': 'Medium'},
    ]


def build_attack_logs(defense_enabled, captured_payload):
    if defense_enabled:
        return [
            '[09:41:12] MITM relay initialized between client and bank-gateway',
            '[09:41:14] Route manipulation attempt accepted by vulnerable client',
            f'[09:41:16] Ciphertext captured: {captured_payload[:48]}...',
            '[09:41:18] Payload unreadable; replay buffer rejected protected packet',
            '[09:41:21] Attack outcome: failed to recover transaction contents',
        ]

    return [
        '[09:41:12] MITM relay initialized between client and bank-gateway',
        '[09:41:14] Route manipulation attempt accepted by vulnerable client',
        f'[09:41:16] Plaintext payload captured: {captured_payload}',
        '[09:41:18] Session token copied to replay buffer',
        '[09:41:21] Attack outcome: transaction details exposed',
    ]


def build_defense_logs(defense_enabled, encrypted):
    if defense_enabled:
        return [
            '[09:41:13] Defender console online',
            '[09:41:15] AES-256-GCM policy applied before packet transit',
            f"[09:41:17] Nonce issued: {encrypted['nonce']}",
            '[09:41:19] Integrity tag verified at bank gateway',
            '[09:41:22] Alert P2 raised; captured packet is unreadable ciphertext',
        ]

    return [
        '[09:41:13] Defender console online',
        '[09:41:15] Packet entropy monitor detected low-entropy payload',
        '[09:41:17] AES-256 policy available but inactive',
        '[09:41:19] Signature verification skipped for plaintext request',
        '[09:41:22] Alert P1 raised for exposed transaction payload',
    ]


def build_defenses(defense_enabled):
    return [
        {'name': 'AES-256 Encryption', 'status': 'Active' if defense_enabled else 'Ready', 'tone': 'green'},
        {'name': 'RSA Key Exchange', 'status': 'Ready', 'tone': 'blue'},
        {'name': 'Digital Signatures', 'status': 'Standby', 'tone': 'yellow'},
        {'name': 'Nonce Protection', 'status': 'Observed' if defense_enabled else 'Standby', 'tone': 'yellow'},
    ]

